--- #YAML:1.0
name:               Test-Spec
version:            0.47
abstract:           Write tests in a declarative specification style
author:
    - Philip Garrett <philip.garrett@icainformatics.com>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Carp:            0
    constant:        0
    Exporter:        0
    List::Util:      0
    Package::Stash:  0.23
    Scalar::Util:    0
    TAP::Parser:     0
    Test::Deep:      0.103
    Test::More:      0
    Test::Trap:      0
    Tie::IxHash:     0
resources:
    repository:  https://github.com/kingpong/perl-Test-Spec
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
